apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-deployment
  labels:
    app: script
spec:
  replicas: 3
  selector:
    matchLabels:
      app: script
  template:
    metadata:
      labels:
        app: script
    spec:
      containers:
      - name: scheduling
        image: scheduling_script:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"

